services:
  postgres-subscribers:
    image: postgres:17-alpine
    container_name: subscribers-db
    expose:
      - "5432"
    networks:
      - subscribers
    volumes:
      - pgdata_subscribers:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_DB: subscribers_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  subscribers-service:
    build:
      context: .
      dockerfile: subscribers/Dockerfile.dev
    container_name: subscribers-service-container
    ports:
      - '8081:8081'
    depends_on:
      postgres-subscribers:
        condition: service_healthy
    networks:
      - all
      - subscribers
    volumes:
      - ./subscribers/build/libs/subscribers.jar:/app/app.jar:ro
    environment:
      POSTGRES_DB: subscribers_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - posts
      - all
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5

  minio-init:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - posts
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      mc mb myminio/posts-bucket --ignore-existing;
      exit 0;
      "

  postgres-posts:
    image: postgres:17-alpine
    container_name: posts-db
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_replication_slots=4"
      - "-c"
      - "max_wal_senders=4"
    networks:
      - posts
    volumes:
      - pgdata_posts:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
    environment:
      POSTGRES_DB: posts_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  post-creator-service:
    build:
      context: .
      dockerfile: post-creator/Dockerfile.dev
    container_name: post-creator-container
    ports:
      - "8082:8082"
    depends_on:
      postgres-posts:
        condition: service_healthy
      minio-init:
        condition: service_completed_successfully
    networks:
      - all
      - posts
      - kafka
    volumes:
      - ./post-creator/build/libs/post-creator.jar:/app/app.jar:ro
    environment:
      POSTGRES_DB: posts_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      S3_ENDPOINT: "http://minio:9000"
      S3_REGION: "us-east-1"
      S3_BUCKET: "posts-bucket"
      S3_ACCESS_KEY: "minioadmin"
      S3_SECRET_KEY: "minioadmin"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'

      KAFKA_LISTENERS: 'CONTROLLER://0.0.0.0:29093,PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'

      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
      KAFKA_CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - kafka
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 | grep 'ApiVersion'" ]
      interval: 10s
      timeout: 10s
      retries: 5

  kafka-connect:
    image: debezium/connect:3.0.0.Final
    container_name: kafka-connect
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: "1"
      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-status
      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xms512M -Xmx512M"
    networks:
      - kafka
      - posts
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8083/connectors || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  debezium-init:
    build:
      context: ./post-creator/kafka-connect
      dockerfile: Dockerfile
    container_name: debezium-init
    depends_on:
      kafka-connect:
        condition: service_healthy
    networks:
      - kafka

  postgres-feed:
    image: postgres:17-alpine
    container_name: feed-db
    expose:
      - "5432"
    networks:
      - feed
    volumes:
      - pgdata_feed:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_DB: feed_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  feed-service:
    build:
      context: .
      dockerfile: feed/Dockerfile.dev
    container_name: feed-container
    ports:
      - "8086:8086"
      - "8087:8087"
    depends_on:
      postgres-feed:
        condition: service_healthy
      kafka:
        condition: service_healthy
      subscribers-service:
        condition: service_started
      minio-init:
        condition: service_completed_successfully
    volumes:
      - ./feed/build/libs/feed.jar:/app/app.jar:ro
    networks:
      - all
      - feed
      - kafka
      - subscribers

volumes:
  pgdata_subscribers:
  minio_data:
  pgdata_posts:
  kafka_data:
  pgdata_feed:

networks:
  all:
    driver: bridge
  subscribers:
    driver: bridge
    internal: true
  posts:
    driver: bridge
    internal: true
  kafka:
    driver: bridge
    internal: true
  feed:
    driver: bridge
    internal: true
