FROM eclipse-temurin:21-jre-alpine

RUN sed -i 's|dl-cdn.alpinelinux.org|mirrors.edge.kernel.org|g' /etc/apk/repositories \
    && apk add --no-cache curl

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

WORKDIR /app

USER appuser
EXPOSE 8082 8085

ENTRYPOINT ["java", "-jar", "app.jar"]