httpServer {
  publicApiHttpPort = 8081

  telemetry {
    logging {
      enabled = true
      stacktrace = true
      pathTemplate = true
    }
  }
}

flyway {
  locations = ["db/migration"]
  enabled = true
  executeInTransaction = true
}

db {
  r2dbcUrl = ${R2DBC_URL}
  r2dbcUrl = "r2dbc:postgresql://postgres-subscribers:5432/subscribers_db"
  jdbcUrl = "jdbc:postgresql://postgres-subscribers:5432/subscribers_db"

  username = ${R2DBC_USER}
  username = "postgres"

  password = ${R2DBC_PASS}
  password = "postgres"

  poolName = "subscriber-pool"
  maxPoolSize = 10
}