httpServer {
    publicApiHttpPort = 8086
    privateApiHttpPort = 8087

    telemetry {
        logging {
            enabled = true
            stacktrace = true
        }
    }
}

httpClient {
    async {
        followRedirects = true
    }
    connectTimeout = 5s
    readTimeout = 10s

    subscribersClient {
        url = "http://subscribers-service-container:8081"
        requestTimeout = 5s

        telemetry {
            logging {
                enabled = true
            }
            metrics {
                enabled = true
            }
        }
    }
}

db {
    r2dbcUrl = "r2dbc:postgresql://postgres-feed:5432/feed_db"
    jdbcUrl = "jdbc:postgresql://postgres-feed:5432/feed_db"
    username = "postgres"
    password = "postgres"
    poolName = "feed-pool"
    maxPoolSize = 10
}

flyway {
    locations = ["db/migration"]
    enabled = true
    executeInTransaction = true
}

s3 {
    endpoint = "http://minio:9000"
    publicEndpoint = "http://localhost:9000"
    region = "us-east-1"
    bucket = "posts-bucket"
    accessKey = "minioadmin"
    secretKey = "minioadmin"
    urlExpirationMinutes = 60
}

kafka {
  consumer {
    feed-listener {
      topics = "sns.Post"
      pollTimeout = 500ms

      driverProperties {
        "bootstrap.servers" = "kafka:9092"
        "group.id" = "feed-service"
        "auto.offset.reset" = "earliest"
        "enable.auto.commit" = "true"
        "auto.commit.interval.ms" = "5000"
        "session.timeout.ms" = "30000"
        "heartbeat.interval.ms" = "10000"
        "max.poll.records" = "100"
        "key.deserializer" = "org.apache.kafka.common.serialization.StringDeserializer"
        "value.deserializer" = "org.apache.kafka.common.serialization.StringDeserializer"
      }

      telemetry {
        logging {
          enabled = true
        }
      }
    }
  }
}