httpServer {
  publicApiHttpPort = 8084

  telemetry {
    logging {
      enabled = true
      stacktrace = true
      pathTemplate = true
    }
  }
}

flyway {
  locations = ["db/migration"]
  enabled = true
  executeInTransaction = true
}

db {
  r2dbcUrl = ${R2DBC_URL}
  r2dbcUrl = "r2dbc:postgresql://postgres-users:5432/users_db"
  jdbcUrl = "jdbc:postgresql://postgres-users:5432/users_db"

  username = ${R2DBC_USER}
  username = "postgres"

  password = ${R2DBC_PASS}
  password = "postgres"

  poolName = "users-pool"
  maxPoolSize = 10
}

jwt {
    secret = ${JWT_SECRET}
    accessTokenTtlSeconds = 900
    refreshTokenTtlSeconds = 604800
}